################################################################################
# File: makefile
# Description: makefile for project 2 client side.
# To execute the makefile, type "make", to delete the executable and 
# transferred shortfile.txt and longfile.txt, # type "make clean".
# To start the client: ftclient <Hostname> <Port> <Command> [Filename] <Port>
# argv[2] is ftp control, argv[4] is ftp data. 
###############################################################################
default:
	cp ftclient.py ftclient
	chmod u+x ftclient

clean:
	rm -f ftclient shortfile.txt longfile.txt
